on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 12 * *" # At 03:30 on day-of-month 12

name: Open release PR

jobs:
  test:
    name: open-release-pr
    uses: kubewarden/github-actions/.github/workflows/reusable-release-pr.yml@ba3d7040a8411ca3ecbd7cb25d20ab9c5be5edd0 # v4.5.0
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
