on: [push, pull_request]
name: Continuous integration
jobs:
  test:
    name: run tests and linters
    uses: kubewarden/github-actions/.github/workflows/reusable-test-policy-rego.yml@ba3d7040a8411ca3ecbd7cb25d20ab9c5be5edd0 # v4.5.0
